language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

install:
   # Deal with all of the DZIL dependancies, quickly and quietly
   - cpanm --quiet --notest Dist::Zilla
   - dzil authordeps | cpanm --quiet --notest
   # Install the lowest possible required version for the dependencies
OLD_CPANM_OPT=$PERL_CPANM_OPT
PERL_CPANM_OPT='--mirror http://cpan.metacpan.org/ --mirror http://search.cpan.org/CPAN '$PERL_CPANM_OPT
STROUT/Import-Into-1.001000.tar.gz
PARSEVAL/List-MoreUtils-0.04.tar.gz
RIEDO/namespace-sweep-0.004.tar.gz
SCHWERN/Test-Simple-0.88.tar.gz
PERL_CPANM_OPT=$OLD_CPANM_OPT
script:
   - dzil smoke --release --author

notifications:
   email: false
   irc:
      - "irc.perl.org#sanity"
